version: "3.8"
services:
  code-server:
    container_name: code-server.cxcxc.pri
    image: codercom/code-server:4.16.0-debian
    volumes:
      - ./data:/home/coder/project
    ports:
      - "8080:8080"
    networks:
      - cxcxc-comprehensive-lab-network

  db:
    container_name: mysqldb.cxcxc.pri
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - cxcxc-comprehensive-lab-network

  gcs-emulator:
    container_name: gcs-emulator.cxcxc.pri
    image: fsouza/fake-gcs-server:1.46
    command: ["-scheme", "http"]
    ports:
      - "4443:4443"
    volumes:
      - ./gcsdata:/data
    networks:
      - cxcxc-comprehensive-lab-network

  adminer:
    container_name: adminer.cxcxc.pri
    image: adminer:4.8.1-standalone
    ports:
      - "8081:8080"
    networks:
      - cxcxc-comprehensive-lab-network

networks:
  cxcxc-comprehensive-lab-network:
